testing_mode = true
payment_provider = "stripe" 
stripe_api_key_test = "sk_test_51Nd13QAVYoCBBkmYrisiaySVNCWuJGkRIOlaMRZNHrDJblZFXI34ZGItaj4Cfrc7gXzbKrKPbuKNI8MD88T1tF3N006ahC9zvH" 
stripe_link_test = "https://buy.stripe.com/test_8wM4jW8q5ay17D2001"
client_id = "160699829241-41id6l6k31lrldck22q3iiuota8tjdel.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'https://netflyp-stock-forecast-app.streamlit.app/'
redirect_url = "https://netflyp-stock-forecast-app.streamlit.app"
