testing_mode = true
payment_provider = "stripe" 
stripe_api_key_test = "rk_test_51Nd13QAVYoCBBkmYwSGGgVB4nBfqT0pVrcdJbGsuFF1qZsuvxed0ASlVYQeRdMXQD9chEATXBrJpihgv4TdUSEMI00qfWt4YE9" 
stripe_link_test = "https://buy.stripe.com/test_7sI03G6hX7lP9LaeUW"
client_id = "160699829241-41id6l6k31lrldck22q3iiuota8tjdel.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'https://netflyp-stock-forecast-app.streamlit.app/'
redirect_url = "https://netflyp-stock-forecast-app.streamlit.app/"
